function [mean_Rnumber,standard_deviation_Rnumber] = geoSIR_determine_reproductive_number(inputs,working,Rzero_or_Fiveday,...
    lockdown_counter,time_days,data_record,n_red,n_yellow,n_white,tot_red,tot_yellow,tot_white,...
    red_zone_increase_numtrips_close,yellow_zone_increase_numtrips_close,white_zone_increase_numtrips_close,...
    red_zone_increase_numtrips_distant,yellow_zone_increase_numtrips_distant,white_zone_increase_numtrips_distant, eruption_counter)
%
% geoSIR, written by Max van wyk de vries and Lekaashree rambabu, 04/2020.
%
%
%This function is used to calculate the mean and standard deviation of various epidimiological variables
%at a given snapshot in time.
%
%determine_reproductive_number(inputs,Rzero_or_Fiveday,

if strcmpi(inputs.Is_there_a_ND,'No') || eruption_counter == 0  %No eruption, or eruption is not ongoing

if strcmpi(Rzero_or_Fiveday, 'Fiveday')

    
averaging_matrix = zeros(inputs.Number_of_iterations_for_R,1);
for five_day_infection = 1:inputs.Number_of_iterations_for_R
    if lockdown_counter == 0
averaging_matrix(five_day_infection,1) = ((1+((data_record(time_days,1)/inputs.Number_of_people)*inputs.Population_density)*...
    (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))+... 
    (((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))^5;
    else
averaging_matrix(five_day_infection,1) = ((1+((data_record(time_days,1)/inputs.Number_of_people)*inputs.Population_density)*...
    (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Lockdown_proportion_non_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_non_symptomatic.max-inputs.Lockdown_proportion_non_symptomatic.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Lockdown_proportion_non_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_non_symptomatic.max-inputs.Lockdown_proportion_non_symptomatic.min))))))+... 
    (((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Lockdown_proportion_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_symptomatic.max-inputs.Lockdown_proportion_symptomatic.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Lockdown_proportion_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_symptomatic.max-inputs.Lockdown_proportion_symptomatic.min))))))^5;
    end
end

mean_Rnumber = mean(averaging_matrix); %Infections in 5 days
standard_deviation_Rnumber = std(averaging_matrix); %Infections in 5 days   
    
    
    
    
    
elseif strcmpi(Rzero_or_Fiveday, 'Rzero')
    
    
averaging_matrix_R = zeros(inputs.Number_of_iterations_for_R,1);
for five_day_infection = 1:inputs.Number_of_iterations_for_R
    if lockdown_counter == 0
averaging_matrix_R(five_day_infection,1) = (((((data_record(time_days,1)/inputs.Number_of_people)*inputs.Population_density)*...
           (((((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))+... %%%%%%%%%%%%%%%%%%
     (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))))*...
               (working.Incubation_time.mean+working.Length_of_illness.mean));
    else
averaging_matrix_R(five_day_infection,1) = (((((data_record(time_days,1)/inputs.Number_of_people)*inputs.Population_density)*...
    (((((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Lockdown_proportion_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_symptomatic.max-inputs.Lockdown_proportion_symptomatic.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Lockdown_proportion_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_symptomatic.max-inputs.Lockdown_proportion_symptomatic.min))))))+... %%%%%%%%%%%%%
    (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Lockdown_proportion_non_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_non_symptomatic.max-inputs.Lockdown_proportion_non_symptomatic.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Lockdown_proportion_non_symptomatic.min + ...
               rand*(inputs.Lockdown_proportion_non_symptomatic.max-inputs.Lockdown_proportion_non_symptomatic.min))))))))*...
               (working.Incubation_time.mean+working.Length_of_illness.mean));
    end
end
mean_Rnumber = mean(averaging_matrix_R);  %Reproductive value
standard_deviation_Rnumber = std(averaging_matrix_R);  %Reproductive value
  
    
    
    
    
end

elseif strcmpi(inputs.Is_there_a_ND,'Yes') && eruption_counter >0  %Eruption is ongoing

Total_n = n_red + n_yellow + n_white;

proportion_red = n_red/Total_n;
proportion_yellow = n_yellow/Total_n;
proportion_white = n_white/Total_n;

if inputs.ND_case == 4 %Account for fact that evacuated zone = higher pop density
    popdens_multiplier = 1-((tot_red + 0.25*tot_yellow )/(tot_red + tot_yellow + tot_white));
elseif inputs.ND_case == 2 || inputs.ND_case == 3
    popdens_multiplier = 1-((tot_red)/(tot_red + tot_yellow + tot_white));
elseif inputs.ND_case == 1
    popdens_multiplier = 1;
end

if strcmpi(Rzero_or_Fiveday, 'Fiveday')

    
averaging_matrix = zeros(inputs.Number_of_iterations_for_R,1); %if eruption is ongoing, never lockdown so can remove that option
for five_day_infection = 1:inputs.Number_of_iterations_for_R

averaging_matrix(five_day_infection,1) = (proportion_red*((1+((data_record(time_days,1)/inputs.Number_of_people)*(inputs.Population_density/popdens_multiplier))*...
    (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((red_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (red_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))+... 
    (((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((red_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (red_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))...
               +...
               proportion_yellow*((1+((data_record(time_days,1)/inputs.Number_of_people)*(inputs.Population_density/popdens_multiplier))*...
    (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((yellow_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (yellow_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))+... 
    (((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((yellow_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (yellow_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))...
               +...
     proportion_white*((1+((data_record(time_days,1)/inputs.Number_of_people)*(inputs.Population_density/popdens_multiplier))*...
    (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((white_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (white_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))+... 
    (((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((white_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (white_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))...      
            )^5;

end

mean_Rnumber = mean(averaging_matrix); %Infections in 5 days
standard_deviation_Rnumber = std(averaging_matrix); %Infections in 5 days   
    

elseif strcmpi(Rzero_or_Fiveday, 'Rzero')
    
    
averaging_matrix_R = zeros(inputs.Number_of_iterations_for_R,1);
for five_day_infection = 1:inputs.Number_of_iterations_for_R
averaging_matrix_R(five_day_infection,1) = (proportion_red*((((data_record(time_days,1)/inputs.Number_of_people)*(inputs.Population_density/popdens_multiplier))*...
           (((((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((red_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (red_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))+... %%%%%%%%%%%%%%%%%%
     (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((red_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (red_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))))...
               +...
      proportion_yellow*((((data_record(time_days,1)/inputs.Number_of_people)*(inputs.Population_density/popdens_multiplier))*...
           (((((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((yellow_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (yellow_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))+... %%%%%%%%%%%%%%%%%%
     (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((yellow_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (yellow_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))))...
               +...
      proportion_white*((((data_record(time_days,1)/inputs.Number_of_people)*(inputs.Population_density/popdens_multiplier))*...
           (((((inputs.Length_of_illness.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %symptomatic. Used MEAN here.
    ((white_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (white_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_symptomatic_self_isolation.max-inputs.Efficiency_of_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_symptomatic_self_isolation.max-inputs.Proportion_symptomatic_self_isolation.min))))))+... %%%%%%%%%%%%%%%%%%
     (((inputs.Incubation_time.mean/(inputs.Incubation_time.mean+inputs.Length_of_illness.mean))*... %non-symptomatic . Used MEAN here.
    ((white_zone_increase_numtrips_close*(inputs.Number_of_close_encounters.min + ...
               rand*(inputs.Number_of_close_encounters.max-inputs.Number_of_close_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_close_encounters.mean,inputs.Probability_of_infection_for_close_encounters.std))+...
    (white_zone_increase_numtrips_distant*(inputs.Number_of_distant_encounters.min + ...
               rand*(inputs.Number_of_distant_encounters.max-inputs.Number_of_distant_encounters.min)))*...
    (normrnd(inputs.Probability_of_infection_for_distant_encounters.mean,inputs.Probability_of_infection_for_distant_encounters.std))))*...
     ((inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))*...
     (1-(inputs.Efficiency_of_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Efficiency_of_non_symptomatic_self_isolation.max-inputs.Efficiency_of_non_symptomatic_self_isolation.min)))+... 
     (1-(inputs.Proportion_non_symptomatic_self_isolation.min + ...
               rand*(inputs.Proportion_non_symptomatic_self_isolation.max-inputs.Proportion_non_symptomatic_self_isolation.min))))))))...
        )*...
               (working.Incubation_time.mean+working.Length_of_illness.mean);

end
mean_Rnumber = mean(averaging_matrix_R);  %Reproductive value
standard_deviation_Rnumber = std(averaging_matrix_R);  %Reproductive value
  
    
    
    
    
end    
    
    
    
    
    
    
    
    
    
    
    
    
    
end %end eruption or not if

